# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /var/www/githubs/vaeql

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /var/www/githubs/vaeql

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /var/www/githubs/vaeql/CMakeFiles /var/www/githubs/vaeql/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /var/www/githubs/vaeql/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named vaeql

# Build rule for target.
vaeql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vaeql
.PHONY : vaeql

# fast build rule for target.
vaeql/fast:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/build
.PHONY : vaeql/fast

VaeQueryLanguageLexer.o: VaeQueryLanguageLexer.cpp.o
.PHONY : VaeQueryLanguageLexer.o

# target to build an object file
VaeQueryLanguageLexer.cpp.o:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageLexer.cpp.o
.PHONY : VaeQueryLanguageLexer.cpp.o

VaeQueryLanguageLexer.i: VaeQueryLanguageLexer.cpp.i
.PHONY : VaeQueryLanguageLexer.i

# target to preprocess a source file
VaeQueryLanguageLexer.cpp.i:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageLexer.cpp.i
.PHONY : VaeQueryLanguageLexer.cpp.i

VaeQueryLanguageLexer.s: VaeQueryLanguageLexer.cpp.s
.PHONY : VaeQueryLanguageLexer.s

# target to generate assembly for a file
VaeQueryLanguageLexer.cpp.s:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageLexer.cpp.s
.PHONY : VaeQueryLanguageLexer.cpp.s

VaeQueryLanguageParser.o: VaeQueryLanguageParser.cpp.o
.PHONY : VaeQueryLanguageParser.o

# target to build an object file
VaeQueryLanguageParser.cpp.o:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageParser.cpp.o
.PHONY : VaeQueryLanguageParser.cpp.o

VaeQueryLanguageParser.i: VaeQueryLanguageParser.cpp.i
.PHONY : VaeQueryLanguageParser.i

# target to preprocess a source file
VaeQueryLanguageParser.cpp.i:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageParser.cpp.i
.PHONY : VaeQueryLanguageParser.cpp.i

VaeQueryLanguageParser.s: VaeQueryLanguageParser.cpp.s
.PHONY : VaeQueryLanguageParser.s

# target to generate assembly for a file
VaeQueryLanguageParser.cpp.s:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageParser.cpp.s
.PHONY : VaeQueryLanguageParser.cpp.s

VaeQueryLanguageTreeParser.o: VaeQueryLanguageTreeParser.cpp.o
.PHONY : VaeQueryLanguageTreeParser.o

# target to build an object file
VaeQueryLanguageTreeParser.cpp.o:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageTreeParser.cpp.o
.PHONY : VaeQueryLanguageTreeParser.cpp.o

VaeQueryLanguageTreeParser.i: VaeQueryLanguageTreeParser.cpp.i
.PHONY : VaeQueryLanguageTreeParser.i

# target to preprocess a source file
VaeQueryLanguageTreeParser.cpp.i:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageTreeParser.cpp.i
.PHONY : VaeQueryLanguageTreeParser.cpp.i

VaeQueryLanguageTreeParser.s: VaeQueryLanguageTreeParser.cpp.s
.PHONY : VaeQueryLanguageTreeParser.s

# target to generate assembly for a file
VaeQueryLanguageTreeParser.cpp.s:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/VaeQueryLanguageTreeParser.cpp.s
.PHONY : VaeQueryLanguageTreeParser.cpp.s

php_vaeql.o: php_vaeql.cpp.o
.PHONY : php_vaeql.o

# target to build an object file
php_vaeql.cpp.o:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/php_vaeql.cpp.o
.PHONY : php_vaeql.cpp.o

php_vaeql.i: php_vaeql.cpp.i
.PHONY : php_vaeql.i

# target to preprocess a source file
php_vaeql.cpp.i:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/php_vaeql.cpp.i
.PHONY : php_vaeql.cpp.i

php_vaeql.s: php_vaeql.cpp.s
.PHONY : php_vaeql.s

# target to generate assembly for a file
php_vaeql.cpp.s:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/php_vaeql.cpp.s
.PHONY : php_vaeql.cpp.s

vaeql.o: vaeql.cpp.o
.PHONY : vaeql.o

# target to build an object file
vaeql.cpp.o:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/vaeql.cpp.o
.PHONY : vaeql.cpp.o

vaeql.i: vaeql.cpp.i
.PHONY : vaeql.i

# target to preprocess a source file
vaeql.cpp.i:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/vaeql.cpp.i
.PHONY : vaeql.cpp.i

vaeql.s: vaeql.cpp.s
.PHONY : vaeql.s

# target to generate assembly for a file
vaeql.cpp.s:
	$(MAKE) -f CMakeFiles/vaeql.dir/build.make CMakeFiles/vaeql.dir/vaeql.cpp.s
.PHONY : vaeql.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... vaeql"
	@echo "... VaeQueryLanguageLexer.o"
	@echo "... VaeQueryLanguageLexer.i"
	@echo "... VaeQueryLanguageLexer.s"
	@echo "... VaeQueryLanguageParser.o"
	@echo "... VaeQueryLanguageParser.i"
	@echo "... VaeQueryLanguageParser.s"
	@echo "... VaeQueryLanguageTreeParser.o"
	@echo "... VaeQueryLanguageTreeParser.i"
	@echo "... VaeQueryLanguageTreeParser.s"
	@echo "... php_vaeql.o"
	@echo "... php_vaeql.i"
	@echo "... php_vaeql.s"
	@echo "... vaeql.o"
	@echo "... vaeql.i"
	@echo "... vaeql.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

